//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebHastaneRandevuSistemiEntities4 : DbContext
    {
        public WebHastaneRandevuSistemiEntities4()
            : base("name=WebHastaneRandevuSistemiEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Branslar> Tbl_Branslar { get; set; }
        public virtual DbSet<Tbl_Cinsiyet> Tbl_Cinsiyet { get; set; }
        public virtual DbSet<Tbl_DoktorAsi> Tbl_DoktorAsi { get; set; }
        public virtual DbSet<Tbl_DoktorCocuk> Tbl_DoktorCocuk { get; set; }
        public virtual DbSet<Tbl_DoktorYetiskin> Tbl_DoktorYetiskin { get; set; }
        public virtual DbSet<Tbl_Hastalar> Tbl_Hastalar { get; set; }
        public virtual DbSet<Tbl_Kullanici> Tbl_Kullanici { get; set; }
        public virtual DbSet<Tbl_Menu> Tbl_Menu { get; set; }
        public virtual DbSet<Tbl_Randevular> Tbl_Randevular { get; set; }
        public virtual DbSet<Tbl_Sekreterler> Tbl_Sekreterler { get; set; }
        public virtual DbSet<Tbl_Tur> Tbl_Tur { get; set; }
    }
}
