//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DoktorCocuk
    {
        public int DoktorCocukid { get; set; }
        public string DoktorCocukAd { get; set; }
        public string DoktorCocukSoyad { get; set; }
        public string DoktorCocukTc { get; set; }
        public string DoktorCocukSifre { get; set; }
        public Nullable<int> DoktorCocukTuridFk { get; set; }
        public Nullable<int> KullaniciidFk { get; set; }
    
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        public virtual Tbl_Tur Tbl_Tur { get; set; }
    }
}
