//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Menu
    {
        public int Menuid { get; set; }
        public string MenuAdi { get; set; }
        public string MenuAdres { get; set; }
        public Nullable<int> MenuSira { get; set; }
        public string MenuYetki { get; set; }
        public string MenuDurum { get; set; }
    }
}
