//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Randevular
    {
        public int Randevuid { get; set; }
        public string RandevuTarih { get; set; }
        public string RandevuSaat { get; set; }
        public string RandevuTur { get; set; }
        public string RandevuDoktor { get; set; }
        public Nullable<bool> RandevuDurum { get; set; }
        public string RandevuBrans { get; set; }
    }
}
