//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sekreterler
    {
        public int Sekreterid { get; set; }
        public string SekreterAd { get; set; }
        public string SekreterSoyad { get; set; }
        public string SekreterTc { get; set; }
        public string SekreterSifre { get; set; }
        public Nullable<int> KullaniciidFk { get; set; }
    
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
    }
}
