//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DoktorYetiskin
    {
        public int DoktorYetiskinid { get; set; }
        public string DoktorYetiskinAd { get; set; }
        public string DoktorYetiskinSoyad { get; set; }
        public Nullable<int> BransidFk { get; set; }
        public string DoktorYetiskinTc { get; set; }
        public string DoktorYetiskinSifre { get; set; }
        public Nullable<int> DoktorYetiskinTuridFk { get; set; }
        public Nullable<int> KullaniciidFk { get; set; }
    
        public virtual Tbl_Branslar Tbl_Branslar { get; set; }
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        public virtual Tbl_Tur Tbl_Tur { get; set; }
    }
}
