//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DoktorAsi
    {
        public int DoktorAsiid { get; set; }
        public string DoktorAsiAd { get; set; }
        public string DoktorAsiSoyad { get; set; }
        public string DoktorAsiTc { get; set; }
        public string DoktorAsiSifre { get; set; }
        public Nullable<int> DoktorAsiTuridFk { get; set; }
        public Nullable<int> KullaniciidFk { get; set; }
    
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        public virtual Tbl_Tur Tbl_Tur { get; set; }
    }
}
